name: autodoc

on:
  push:
    branches: [ "main", "feature/*", "*" ]
  pull_request:
    branches: [ "main", "feature/*", "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        OPENAI_TOKEN: ${{ secrets.OPENAI_KEY }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo pip install pycodestyle
        pip install pdoc3
        echo api_token=$API_TOKEN >> user.properties
        echo openai_key=$OPENAI_TOKEN >> user.properties
    - name: Add folders to Python Path
      run: |
          echo "PYTHONPATH=code" >> $GITHUB_ENV
    - name: Auto Generate Documentation
      run: |
        echo "PYTHONPATH=./code" >> $GITHUB_ENV
        pdoc --html code --force --output-dir docs
        echo "Github reference"
        echo ${{ github.ref }}
        git add .
        git config --local user.name "autodoc"
        git config --local user.email "actions@github.com"
        git diff-index --quiet HEAD || git commit -m "CI: Automated build push" -a
    - name: Push Documentation
      if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
